  <title>Valnice - Insejec São José dos Campos</title>
<style>
    #hero .container { min-height: 60vh;} 
</style>
 
<!-- Welcome Section -->
<section id="inicio">
<section id="welcome_txt">
    <div class="welcome_txt container">
      <div class="welcome_txt-top">
        <h1 class="section-title">Valnice Milhomens</h1>
        <p>
        A Igreja Nacional do Senhor Jesus Cristo (INSEJEC) se confunde com a trajetória de Valnice Milhomens Coelho, o canal de Deus para o seu estabelecimento, como uma das agências do Reino de Deus na terra.  Nascida em 16 de julho de 1947, em Carolina, MA, filha de Osvaldo Coelho e Aurenice Milhomens Coelho, cresceu em Tocantínia-TO, onde foi aluna da missionária Margarida Lemos Gonçalves, no jardim de infância e, depois, da missionária Beatriz Silva, na quarta série, tendo cursado o Ginásio Batista de Tocantínia. Converteu-se, aos 15 anos (20.06.1963), lendo a Bíblia sozinha, dos 12 aos 15. Foi chamada para o ministério ao 16, com a morte da missionária Margarida de Aguiar Natividade (09.02.1964). Marcada pela vida e testemunho missionários, partiu, aos 17 anos, para o Seminário de Educadores Cristãos, em Recife, PE, onde estudou por seis anos. Aos 23 foi nomeada a primeira missionária à África, pela Junta de Missões Mundiais da Convenção Batista Brasileira (27.11.1970). Serviu como tal em Moçambique por 13 anos, cerca de dez dos quais, como a única missionária evangélica no País, em meio ao comunismo. Depois viveu dois anos na África do Sul, onde mergulhou num poderoso avivamento e recebeu o chamado de volta ao Brasil.
        <br><br>
        <b>MINISTÉRIO ITINERANTE NO BRASIL</b> - Valnice recebeu um chamado sobrenatural de Deus, durante uma Escola de Ministério, em Pretória (08.02.1985): “Tenho um ministério para ti no Brasil. Treina-me um exército!” Retornou ao Brasil (22.11.1985), direto a um lugar de jejum e oração, a fim de ouvir os comandos do Pai. Obedecendo ao que recebeu, deu início ao seu ministério no Brasil, com base em Recife (02.02.1986), viajando extensamente, em conferências de avivamento, a convite de Igrejas e Seminários, o que fez por oito anos ininterruptos.
        <br><br>
        <b>MINISTÉRIO PALAVRA DA FÉ</b> - A fim de atender às demandas de um ministério em expansão, ele se tornou uma personalidade jurídica (05.12.1987), com sede em Recife, onde foi reconhecido de utilidade pública, municipal e estadual. Adquiriu sua primeira sede própria em 08.03.1989, que se tornou o centro de treinamento dos Guerreiros de Oração pela nação.  Mudou-se para São Paulo (11.1992) e estabeleceu a última sede em São José dos Campos-SP (01.08.1993), onde o ministério recebeu a doação de um belo e grande patrimônio, feita pelo casal José e Marina Felício. Seu propósito principal: AVIVAMENTO, mobilização e treinamento de um exército de intercessores pela redenção do Brasil, chamados “Guerreiros de Oração,” vindo depois o ministério na TV. Pelos seminários, abordando diversos temas negligenciados por muitos, buscou edificar o Corpo de Cristo. Em meio aos seminários de avivamento, jornadas de jejum e oração, incontáveis eram convertidos, libertos, curados e edificados.
        <br><br>
        <b>MINISTÉRIO NA TELEVISÃO</b> - Por instrumentalidade do Pr. Flavio Grassano, empresário em São Paulo, entrou na Rede Bandeirantes de Televisão, com um programa de uma hora (24.06.1994), chamado “A PALAVRA DA FÉ.” Depois de três meses, o próprio Ministério abraçou o desafio de fé para manter-se na televisão. Em 1994 (22.08) teve início um novo programa, de segunda a sexta, de meia-hora, chamado ESCOLA BÍBLICA NA TV. Largos milhares de vidas foram alcançados e o Reino de Deus foi expandido. Inúmeros ministérios surgiram, como fruto desse ministério, que só a eternidade poderá contabilizar. Valnice ministrou pela Televisão por 23 anos ininterruptos, recebendo direção de nos anos futuros focar no treinamento de líderes, através da Internet.
        <br><br>
        <b>INVESTIDURAS MINISTERIAIS</b> - Valnice foi ordenada Missionária (05.12.1987), por um concílio interdenominacional, presidido pelo Pr. José Linaldo de Oliveira, dia em que nasceu o Ministério Palavra da Fé, do qual é Presidente e fundadora. Foi ordenada Pastora (30.04.1993), por um Concílio de Pastores de diversas denominações, por iniciativa do Pr. João Batista Martins de Sá, Presidente e fundador da Igreja Batista Ágape, em Campinas, SP. Sua ordenação como pastora foi mais um reconhecimento, que abriu caminho para uma série de ordenações de mulheres, tornando-se um ministério respeitado na nação. Foi comissionada apóstola (05.08.201), por voto comum de pastores de diversas denominações, sob liderança do apóstolo Rony Chaves. Todas essas investiduras ocorreram por iniciativa de pastores que reconhecem seu ministério, sendo ela mesma surpreendida em cada ocasião, recebendo-as em lágrimas e temor.
        <br><br>
        <b>INSEJEC</b> – Em 28 de março de 1994, na sede do Ministério Palavra da Fé, em São José dos Campos, SP, nasceu espiritualmente a Igreja Nacional do Senhor Jesus Cristo, sem qualquer plano prévio, para surpresa de todos. Logo após o batismo de dois seminaristas católicos, convertidos pelo programa de TV “A Palavra da Fé”, sob um comando do Espírito de Deus, e a promessa de que “O Espírito vos guiará a toda verdade.” Em 20 de junho do mesmo ano, reuniram-se as congregações “Palavra da Fé” para se constituírem oficialmente em Igreja Nacional do Senhor Jesus Cristo – INSEJEC. Esta é uma Igreja com forte visão de formação do caráter de Cristo nos seus discípulos, de retorno ao modelo da Igreja Primitiva em Jerusalém (no templo e nas casas) e da Redenção da Pátria e dos povos não alcançados. É hoje uma igreja em Células.
        <br><br>
        <b>FORMAÇÃO ACADÊMICA</b> – Valnice é Bacharel em Assistência Social e Educação Religiosa, pelo Seminário de Educadores Cristãos; Bacharel em Teologia pela Faculdade de Teologia Integrada, Recife, PE (diploma averbado pela Universidade Federal de Pernambuco); mestre de Artes em Liderança Organizacional, pela Azusa Pacific University (CA, EUA); Mestre em Teologia – Faculdade Latino Americana de Teologia e Ciências Humanas (Guarulhos, SP), Doutora em Teologia e Ministério Pastoral, pela Latin University of Theology, Los Angeles (CA, EUA).
        <br><br>
        <b>ISRAEL</b> – Desde o início do seu ministério no Brasil, Valnice envolveu-se com Israel, tendo realizado ali, entre 1987 e março de 2015, vinte e três congressos proféticos. Em comemoração do seu jubileu de ouro ministerial, escreveu um livro sobre Israel, Jordânia Bíblica e a Turquia nos dias bíblicos, destacando os locais onde ministrou em um congresso, no caminho, de 21 dias. Recebeu reconhecimento do Ministério de Turismo de Israel e homenagem do prefeito de Tiberíades, com a chave da cidade. Muitos pastores receberam dela o ensino e a visão sobre Israel e passaram a levar suas próprias caravanas e a interceder pela redenção do povo de Jesus. Como em tudo o que faz, este ministério tem se reproduzido.
        <br><br>
        <b>PRODUÇÃO LITERÁRIA</b> – Valnice é uma profícua escritora, tendo sua própria editora (www.palavradafe.com.br). Já publicou 14 livros para além de grande número de estudos em áudio, vídeo e artigos. Seus best sellers, “Personalidades Restauradas” e “Orando a Palavra”, já atingiram a marca de 13 e 16 impressões, respectivamente, sendo que “Orando a Palavra” encontra-se na segunda impressão de uma nova versão.
        <br><br>
        Muito mais poderia ser dito sobre o perfil de Valnice, que completou em 2015 cinquenta anos de ministério (incluindo os seis de seminário, durante os quais usou todo o tempo disponível e as férias para servir às Igrejas). Tem desenvolvido no País um ministério de pregação, ensino, oração e avivamento, sem fronteiras denominacionais. Pelo ministério de televisão, de multimídia e de farta literatura que tem produzido, busca atingir as vidas que, aos milhares, se têm rendido aos pés do Senhor Jesus e sido discipuladas. Tem sido, verdadeiramente, uma voz profética incontestável nestes últimos tempos. Seu ministério se caracteriza fortemente por uma unção de ensino e treinamento de obreiros e pastores. Nisso tem investido sua vida nos últimos anos. A multiplicação de discípulos, líderes e Igrejas, é seu foco de ação ministerial. Treinar líderes que reproduzam o caráter de Cristo e Sua missão, é no que se empenha com denodo.
        <br><br>
        Valnice, é conhecida por seu caráter integro, firme e ousado, e um incontido amor a Jesus, ao perdido e à Sua Igreja. Considera-se apenas uma serva de Jesus Cristo. Como tal, busca viver a aliança feita com Deus, antes de entrar no Seminário: “Vou sempre te obedecer, sem nunca Te questionar, e confiar em Ti, em todas as circunstâncias.”
        <br><br>
        Seu moto de vida:  “Em nada considero  minha vida preciosa para mim mesma, contanto que cumpra com alegria a minha carreira, e o ministério que recebi do Senhor Jesus, para dar testemunho do evangelho da graça de Deus” (Atos 20:24).
        <br><br>
        Reconhecida internacionalmente como uma capitã de oração e ensino profético, é enfática ao concluir a respeito de suas ações: “Nada tem a ver comigo. Tudo tem a ver com Ele (Deus). Tudo o que devo fazer é crer e obedecer.”
        </p>
      </div>
</div>
</section>
</section>
<!-- End Welcome Section -->
