name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FTP client
      run: sudo apt-get install lftp

    - name: Deploy to cPanel via FTP
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -f "
        open ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_SERVER
        mirror -R ./ /public_html --ignore-time --parallel=10
        quit
        "
